# Generated by Django 3.1.7 on 2021-05-10 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('BE', 'Beginner'), ('IN', 'Intermediate'), ('AD', 'Advanced')], max_length=100)),
                ('plan_length', models.CharField(choices=[('2W', '2'), ('4W', '4'), ('8W', '8')], max_length=100)),
                ('days_per_week', models.CharField(choices=[('3D', '3 Days'), ('4D', '4 Days'), ('5D', '5 Days')], max_length=100)),
                ('time_per_workout', models.CharField(choices=[('3D', '30 Min'), ('4D', '45 Min'), ('5D', '60 Min')], max_length=100)),
                ('equipment', models.CharField(choices=[('NE', 'No equipment'), ('DB', 'Dumbbell'), ('GM', 'Gym')], max_length=100)),
                ('main_goal', models.CharField(choices=[('NE', 'Lose Fat'), ('DB', 'Build Muscle'), ('GM', 'Get Fit')], max_length=100)),
                ('image', models.ImageField(default='default_exercise.jpg', upload_to='program_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
