# Generated by Django 3.1.7 on 2021-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='image',
            field=models.ImageField(blank=True, default='default_exercise.jpg', upload_to='program_pics'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_length',
            field=models.CharField(choices=[('2W', '2 Week'), ('4W', '4 Week'), ('8W', '8 Week')], max_length=100),
        ),
    ]
