# Generated by Django 3.1.7 on 2021-04-28 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210428_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
