# Generated by Django 3.1.7 on 2021-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20210428_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='plan_length',
            field=models.CharField(choices=[('2W', '2'), ('4W', '4'), ('8W', '8')], max_length=100),
        ),
    ]
