# Generated by Django 3.1.7 on 2021-05-04 00:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default_exercise.jpg', upload_to='exercise_pics')),
                ('description', models.TextField(blank=True)),
                ('focus', models.CharField(choices=[('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Core'), ('BK', 'Back'), ('CH', 'Chest'), ('SH', 'Shoulders'), ('FB', 'Full Body'), ('CA', 'Cardio'), ('YP', 'Yoga Pose')], max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MainExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=100000)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('mainexerciseset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.mainexerciseset')),
                ('set_num', models.PositiveIntegerField(default=4, verbose_name='Number of sets')),
                ('rep_num', models.IntegerField(verbose_name='Repetitions')),
                ('rep_type', models.CharField(choices=[('RE', 'rep(s)'), ('SE', 'sec(s)')], default='RE', max_length=2, verbose_name='Unit')),
                ('weight_num', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Weight')),
                ('weight_type', models.CharField(choices=[('KG', 'kg'), ('BW', 'bodyweight')], default='KG', max_length=2, verbose_name='Unit')),
                ('rest_time', models.IntegerField(default=0, verbose_name='Rest Time')),
            ],
            options={
                'ordering': ['order'],
            },
            bases=('base.mainexerciseset',),
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('workout_day', models.DateField(default=datetime.date.today)),
                ('training_type', models.CharField(choices=[('HI', 'HIIT'), ('ST', 'Strength Training'), ('YO', 'Yoga'), ('CA', 'Cardio')], max_length=100)),
                ('body_focus', models.CharField(choices=[('UP', 'Upper Body'), ('LW', 'Lower Body'), ('CR', 'Core'), ('TL', 'Total Body')], max_length=100)),
                ('plan_week', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_day', models.PositiveIntegerField(blank=True, null=True)),
                ('favorites', models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL)),
                ('plan_user', models.ManyToManyField(blank=True, related_name='workouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workoutplan')),
            ],
            options={
                'ordering': ['-workout_day'],
            },
        ),
        migrations.AddField(
            model_name='mainexerciseset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workout'),
        ),
    ]
