# Generated by Django 3.1.7 on 2021-04-11 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='default_exercise.jpg', upload_to='exercise_pics')),
                ('description', models.TextField(blank=True)),
                ('focus', models.CharField(choices=[('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Core'), ('BK', 'Back'), ('CH', 'Chest'), ('SH', 'Shoulders'), ('FB', 'Full Body'), ('CA', 'Cardio')], default='CR', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.PositiveIntegerField(default=4, verbose_name='Number of sets')),
                ('rep_num', models.IntegerField(verbose_name='Repetitions')),
                ('rep_type', models.CharField(choices=[('RE', 'rep(s)'), ('SE', 'sec(s)')], default='RE', max_length=2, verbose_name='Unit')),
                ('weight_num', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Weight')),
                ('weight_type', models.CharField(choices=[('KG', 'kg'), ('BW', 'bodyweight')], default='KG', max_length=2, verbose_name='Unit')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.workout')),
            ],
        ),
    ]
