# Generated by Django 3.1.7 on 2021-04-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210411_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='body_focus',
            field=models.CharField(blank=True, choices=[('UP', 'Upper Body'), ('LW', 'Lower Body'), ('CR', 'Core'), ('TL', 'Total Body')], max_length=100, null=True),
        ),
    ]
