# Generated by Django 3.1.7 on 2021-04-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210412_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='training_type',
            field=models.CharField(blank=True, choices=[('---------', 'All'), ('HI', 'HIIT'), ('ST', 'Strength Training'), ('YO', 'Yoga')], default='All', max_length=100, null=True),
        ),
    ]
