# Generated by Django 3.1.7 on 2021-04-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210412_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='focus',
            field=models.CharField(choices=[(None, 'All'), ('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Core'), ('BK', 'Back'), ('CH', 'Chest'), ('SH', 'Shoulders'), ('FB', 'Full Body'), ('CA', 'Cardio')], default=None, max_length=2),
        ),
    ]
