# Generated by Django 3.1.7 on 2021-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20210412_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='focus',
            field=models.CharField(choices=[('', 'All'), ('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Core'), ('BK', 'Back'), ('CH', 'Chest'), ('SH', 'Shoulders'), ('FB', 'Full Body'), ('CA', 'Cardio')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workout',
            name='body_focus',
            field=models.CharField(blank=True, choices=[('UP', 'Upper Body'), ('LW', 'Lower Body'), ('CR', 'Core'), ('TL', 'Total Body')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_type',
            field=models.CharField(blank=True, choices=[('HI', 'HIIT'), ('ST', 'Strength Training'), ('YO', 'Yoga')], max_length=100, null=True),
        ),
    ]
