# Generated by Django 3.1.7 on 2021-04-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210412_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='focus',
            field=models.CharField(choices=[('AR', 'Arms'), ('LG', 'Legs'), ('CR', 'Core'), ('BK', 'Back'), ('CH', 'Chest'), ('SH', 'Shoulders'), ('FB', 'Full Body'), ('CA', 'Cardio'), ('YP', 'Yoga Pose')], max_length=2),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_type',
            field=models.CharField(blank=True, choices=[('HI', 'HIIT'), ('ST', 'Strength Training'), ('YO', 'Yoga'), ('CA', 'Cardio')], max_length=100, null=True),
        ),
    ]
