# Generated by Django 3.1.7 on 2021-04-19 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210416_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-workout_day']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_day',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
