# Generated by Django 3.1.7 on 2021-04-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('base', '0011_auto_20210419_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_plan',
            field=models.ManyToManyField(blank=True, null=True, to='workouts.WorkoutPlan'),
        ),
    ]
