# Generated by Django 3.1.7 on 2021-04-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('base', '0012_auto_20210426_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_plan',
            field=models.ManyToManyField(blank=True, to='workouts.WorkoutPlan'),
        ),
    ]
