# Generated by Django 3.1.7 on 2021-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210426_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
