# Generated by Django 3.1.7 on 2021-04-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_workout_plan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
