# Generated by Django 3.1.7 on 2021-04-29 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_auto_20210429_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='plan_user',
            field=models.ManyToManyField(related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
